### ISSUE TITLE
Docs: Add example of using jsclass without the package manager

### ISSUE THREAD

**Issue by Izhaki** [jcoglan/jsclass#40]
I recently came across the library, searching for a js oop solution.

The library is amazing, the package manager is amazing, but the coupling between then in the docs is somewhat confusing and nearly deterred me from the whole library.
# What myself and others may be after

I was after a library that allows me to simply add it to the client side, and start using it.

I you look at [jsface](https://github.com/tnhu/jsface), for instance, the instructions say you add:

```
<script src="jsface.js" type="text/javascript"></script>
```

And then can write:

```
var Person = Class({
  constructor: function(name, age) {
    this.name = name;
    this.age  = age;
  },

  toString: function() {
    return this.name + "/" + this.age;
  }
});

var person = new Person("Rika", 20);
person.toString(); 
```
# What I have found

Now instead, I found quite a bit of docs explaining how to use the package management.

In my case, jsclass will live with AngularJS (which has its own package management system), and I need to write around 70 classes, distributed into folder hierarchy, and for starters - the whole thing is just grunt concat to one big library. Having to wring manifast files and wrapping each class with a dependency code is quite an overkill, particularly at these early stages of the project. 

While using the package manager could be the right thing at the long run, currently I'm just after something simple like jsface.
# It's really easy

The solution to my problem was super easy. And yes - I am maybe a bit daft for taking so long to work it out, but the whole discussion about the package management (and jsbuild) threw me off in the completely wrong direction.

Essentially, one shall just add:

```
     <script src="/libs/jsclass/core.js"></script>
```

And then write:

```
var Animal = new JS.Class({
    initialize: function(name) {
        this.name = name;
    },

    speak: function(things) {
        console.log( 'My name is ' + this.name + ' and I like ' + things );
    }
});

var nemo = new Animal('Nemo');    // nemo.name == "Nemo"

nemo.speak('swimming');
```

If this example would be given in [the Getting Started guide](http://jsclass.jcoglan.com/introduction.html) it would save me about 3 hours.

I really think the example above should be added - I nearly gave up the whole library because I really needed the layer of complexity the package manager involved - I only needed an oop class library. I'd assume others would share the same needs as me.

**Comment by chatchavan** [comment]
+1

**Comment by artemrizhov** [comment]
+1

**Comment by oddjobz** [comment]
+1 .. and [a bit more here ...](https://gareth.bult.co.uk/2016/01/16/javascript-and-proper-classes/)

**Comment by pzolla** [comment]
+1
